version: '2'

services:
  main:
    image: moul/liquidsoap
    volumes:
      - ./config:/config
      - ./playlists:/playlists
      - ./data:/data
      - ./timezone:/etc/localtime:ro 
    command: /bin/bash -xc 'env; /supervisor.sh liquidsoap -v --debug /config/main.liq'
    environment:
      - HARBOR_PASSWORD
      - LIVE_PASSWORD
      - BROADCAST_PORT_5001_TCP_ADDR=broadcast
      - BROADCAST_PORT_5001_TCP_PORT=5001
      - VIRTUAL_HOST=live.ravepartyradio.org
      - VIRTUAL_PORT=8022
    env_file: .env
    links:
      - broadcast
    ports:
      - 8021:5001
      - 8022:5002
      - 127.0.0.1:5000:5000
  
  broadcast:
    image: moul/liquidsoap
    volumes:
      - ./config:/config
      - ./playlists:/playlists
      - ./timezone:/etc/localtime:ro 
    command: /bin/bash -xc 'env; /supervisor.sh liquidsoap -v --debug /config/broadcast.liq'
    environment:
      - HARBOR_PASSWORD
      - ICECAST_SOURCE_PASSWORD
      - ICECAST_PORT_8000_TCP_ADDR=icecast
      - ICECAST_PORT_8000_TCP_PORT=8000
    env_file: .env
    links:
      - icecast
    ports:
      - 5001
  
  icecast:
    image: moul/icecast
    volumes:
      - ./logs/icecast2:/var/log/icecast2
      - ./timezone:/etc/localtime:ro 
    networks:
      - default
      - service-proxy
    environment:
      - VIRTUAL_HOST=icecast.ravepartyradio.org
      - VIRTUAL_PORT=8000
      - ICECAST_SOURCE_PASSWORD
      - ICECAST_ADMIN_PASSWORD
      - ICECAST_PASSWORD
      - ICECAST_RELAY_PASSWORD
    env_file: .env
    ports:
      - 8000:8000
    restart: always
  
  webftp:
    image: httpd
    ports:
      - 8024:80
    volumes:
      - ./playlists:/usr/local/apache2/htdocs/playlists
      - ./trucs:/usr/local/apache2/htdocs/trucs
      - ./data:/usr/local/apache2/htdocs/data
    networks:
      - default
      - service-proxy
    environment:
      - VIRTUAL_HOST=ftp.ravepartyradio.org
      - VIRTUAL_PORT=8024

  admin:
    image: tutum/apache-php
    ports:
      - 8080:80
    volumes:
      - ./timezone:/etc/localtime:ro
      - ./admin:/app
    networks:
      - default
      - service-proxy
    environment:
      - VIRTUAL_HOST=admin.ravepartyradio.org
      - VIRTUAL_PORT=8080
      - ICECAST_ADMIN_PASSWORD
      - MAIN_PORT_5000_TCP=tcp://main:5000
    env_file: .env
    links:
      - main

  site:
    image: tutum/apache-php
    ports:
      - 80:80
    volumes:
      - ./site:/app
    networks:
      - default
      - service-proxy

networks:
  service-proxy:
    external: true